<a href="https://colab.research.google.com/github/hemalatha2205/Data_Science/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(
    {
        "Student Name" : ["Hema","Satwika","Bhavya"],
        "Age" : [20,np.nan,19],
        "Gender": ['F',np.nan,'F'],
        "Department": ['CSE','CSE',np.nan]
    }
    )

In [5]:
df

  Student Name   Age Gender Department
0         Hema  20.0      F        CSE
1      Satwika   NaN    NaN        CSE
2       Bhavya  19.0      F        NaN

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

  Student Name   Age Gender Department
0         Hema  20.0      F        CSE
1      Satwika  19.5    NaN        CSE
2       Bhavya  19.0      F        NaN

In [7]:
df['Department'] = df['Department'].ffill()
df

  Student Name   Age Gender Department
0         Hema  20.0      F        CSE
1      Satwika  19.5    NaN        CSE
2       Bhavya  19.0      F        CSE

In [8]:
df['Gender'] = df['Gender'].bfill()
df

  Student Name   Age Gender Department
0         Hema  20.0      F        CSE
1      Satwika  19.5      F        CSE
2       Bhavya  19.0      F        CSE